//CfLv3Real.java
package com.gof.entity;

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.gof.enums.EBoolean;
import com.gof.enums.ECfType;
import com.gof.enums.EContStatus;
import com.gof.enums.ELiabType;
import com.gof.enums.ETiming;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
* CfLv3Real generated by hbm2java
*/
@Entity
@Table(name = "CF_LV3_REAL")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CfLv3Real implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;
	
	
	
//	 SEQ PK부여
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "PK_SEQUENCE_JPA")
	private Long pkSeq;
	
	private String baseYymm;
	private String gocId;
	
	@Enumerated(EnumType.STRING)
	private ELiabType liabType;
	
	@Enumerated(EnumType.STRING)
	private EContStatus stStatus;
	
	@Enumerated(EnumType.STRING)
	private EContStatus endStatus;
	
	@Enumerated(EnumType.STRING)
	private EBoolean newContYn;
	
	private String cfKeyId;
	
	@Enumerated(EnumType.STRING)
	private ECfType cfType;
	
	@Enumerated(EnumType.STRING)
	private EBoolean outflowYn;
	
	private String cfStartYymm;
	private String cfEndYymm;
	
	private Double cfAmt;
	
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;

	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
	public ETiming getCfTiming() {
		return ETiming.END;
	}

	public Double getCfMonthNum() {
		return 0.0;
	}
	
	public boolean isFutureCf(double forwardingNum) {
		return false;
	}
	
	@Override
	public String toString() {
		 StringBuilder 	builder = new StringBuilder();
	 	 return builder
	 		.append(baseYymm).append(",")
	 	 	.append(gocId).append(",")
	 	 	.append(stStatus).append(",")
	 	 	.append(endStatus).append(",")
	 	 	.append(newContYn).append(",")
	 	 	.append(cfType).append(",")
	 	 	.append(cfAmt).append(",")
	 	 	.toString();
	}
	
}
