//MapRunsetCalc.java
package com.gof.entity;
//Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
* MstBoxCoa generated by hbm2java
*/
@Entity
@Table(name = "MAP_RUNSET_CALC")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
//@Slf4j
public class MapRunsetCalc implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "PK_SEQUENCE_JPA")
	private Long pkSeq;
	
	@ManyToOne
	@JoinColumn(name = "RUNSET_ID")
	private MstRunset mstRunset;
	
	@ManyToOne
	@JoinColumn(name = "CALC_ID")
	private MstCalc mstCalc;
	
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;

//	@Transient
//	private List<ECfType> cfTypeList;	
	
//	public void setCfTypeList(List<ECfType> cfTypeList) {
//		this.cfTypeList = cfTypeList;
//	}
	
//	public boolean contains(ECfType cfType) {
//		return cfGroup.contatins(cfType);
//	}
	
	public String getRunsetId() {
		return mstRunset.getRunsetId();
	}
	
	public String getCalcId() {
		return mstCalc.getCalcId();
	}
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	
	@Override
	public int hashCode() {
		return super.hashCode();
	}
}

