package com.gof.entity;


import javax.persistence.Embeddable;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;

import com.gof.enums.EBoolean;
import com.gof.enums.EContStatus;
import com.gof.enums.ELiabType;

import lombok.Getter;

/**
* AcctBoxId generated by hbm2java
*/
@Embeddable
@Getter
public class MetaInfoId implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;
	
	private String tableCatalog;
	private String tableSchema;
	private String tableName;
	private String columnName;
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	@Override
	public String toString() {
		 StringBuilder 	builder = new StringBuilder();
	 	 return builder
	 		.append(tableCatalog).append(",")
	 	 	.append(tableSchema).append(",")
	 	 	.append(tableName).append(",")
	 	 	.append(columnName).append(",")
	 	 	.toString();
	}
	
}





	

