//TvogLv1.java
package com.gof.entity;
//Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
* RstRa generated by hbm2java
*/
@Entity
@Table(name = "TVOG_LV1")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TvogLv1 implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "PK_SEQUENCE_JPA")
	private Long pkSeq;	
	
	private String baseYymm;
	private String gocId;
	
	
//	@ManyToOne
//	@JoinColumn(name = "RUNSET_ID")
	
	private String runsetId;
	
	private String deltaGroup;
	
	
	private Double tvogAmt;
	private String srcBaseYymm;
	private String rsDivId;

	
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;
	
	public String getDeltaGroupPk() {
		return gocId+deltaGroup;
	}
	
	public String getDeltaGroupPk(String priorDeltaGroup) {
		return gocId+priorDeltaGroup;
	}
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
}
